### ISSUE TITLE
Python cannot resolve import 

### ISSUE THREAD

**Issue by zachaa2** [j4mesli/cs2leaderboard-APY#1]
I'm using your sample code and it's not working !11111!!1!1!!!1!1!
Despite running pip install, Python cannot resolve the import!
```
import cs2apy as cs2
africa = cs2.fetch_africa()
print(africa)
```
HELP ME 😭😭😭😭😭

**Comment by j4mesli** [comment]
Fixed it, should work now. Run this:
```
pip install --upgrade --force-reinstall CS2APY
```
